/**
 * Alphabetized US + Commonwealth military ranks (Army, Navy, Air Force, Marines, historical variants)
 * for rank autocomplete in hero forms.
 */
const MILITARY_RANK_LINES = [
  "Able Seaman",
  "Acting Sub-Lieutenant",
  "Admiral",
  "Admiral of the Fleet",
  "Air Chief Marshal",
  "Air Commodore",
  "Air Marshal",
  "Air Vice-Marshal",
  "Airman",
  "Airman Basic",
  "Airman First Class",
  "Apprentice",
  "Bombardier",
  "Boy Seaman",
  "Brigadier",
  "Brigadier General",
  "Bugler",
  "Cadet",
  "Captain",
  "Captain (Navy)",
  "Captain of the Fleet",
  "Chief Master Sergeant",
  "Chief Master Sergeant of the Air Force",
  "Chief Master Sergeant of the Space Force",
  "Chief Petty Officer",
  "Chief Warrant Officer 2",
  "Chief Warrant Officer 3",
  "Chief Warrant Officer 4",
  "Chief Warrant Officer 5",
  "Colonel",
  "Colour Sergeant",
  "Command Chief Master Sergeant",
  "Command Chief Warrant Officer",
  "Command Master Chief Petty Officer",
  "Command Sergeant Major",
  "Commander",
  "Commodore",
  "Conductor",
  "Corporal",
  "Corporal of Horse",
  "Cornet",
  "Driver",
  "Drummer",
  "Ensign",
  "Ensign (Historical Commonwealth)",
  "Farrier",
  "Field Marshal",
  "First Lieutenant",
  "First Sergeant",
  "Fleet Admiral",
  "Flight Lieutenant",
  "Flight Sergeant",
  "Flying Officer",
  "Fusilier",
  "General",
  "General of the Air Force",
  "General of the Army",
  "Group Captain",
  "Guardsman",
  "Gunner",
  "Gunnery Sergeant",
  "Havildar (Indian Army / CW Historical)",
  "Hospital Corpsman",
  "Jemadar (Indian Army / CW Historical)",
  "Junior Technician",
  "Kingsman",
  "Lance Bombardier",
  "Lance Corporal",
  "Lance Sergeant",
  "Leading Aircraftman",
  "Leading Seaman",
  "Lieutenant",
  "Lieutenant (Junior Grade)",
  "Lieutenant Colonel",
  "Lieutenant Commander",
  "Lieutenant General",
  "Major",
  "Major General",
  "Marine",
  "Master Aircrew",
  "Master Chief Petty Officer",
  "Master Chief Petty Officer of the Coast Guard",
  "Master Chief Petty Officer of the Navy",
  "Master Corporal",
  "Master Gunnery Sergeant",
  "Master Seaman",
  "Master Sergeant",
  "Master Warrant Officer",
  "Midshipman",
  "Musician",
  "Naik (Indian Army / CW Historical)",
  "Officer Cadet",
  "Ordinary Seaman",
  "Petty Officer",
  "Petty Officer First Class",
  "Petty Officer Second Class",
  "Petty Officer Third Class",
  "Pilot Officer",
  "Pioneer",
  "Piper",
  "Private",
  "Private (Basic)",
  "Private First Class",
  "Quartermaster Sergeant",
  "Ranger",
  "Rear Admiral",
  "Rear Admiral (Lower Half)",
  "Rear Admiral (Upper Half)",
  "Recruit",
  "Regimental Sergeant Major",
  "Rifleman",
  "Sapper",
  "Seaman",
  "Seaman Apprentice",
  "Seaman Recruit",
  "Second Lieutenant",
  "Senior Aircraftman",
  "Senior Chief Petty Officer",
  "Senior Master Sergeant",
  "Sepoy (Indian Army / CW Historical)",
  "Sergeant",
  "Sergeant First Class",
  "Sergeant Major",
  "Sergeant Major of the Army",
  "Sergeant Major of the Marine Corps",
  "Signaller",
  "Skipper",
  "Space Force Specialist 1",
  "Space Force Specialist 2",
  "Space Force Specialist 3",
  "Space Force Specialist 4",
  "Specialist",
  "Squadron Leader",
  "Staff Sergeant",
  "Staff Sergeant Major",
  "Sub-Lieutenant",
  "Subedar (Indian Army / CW Historical)",
  "Subedar-Major (Indian Army / CW Historical)",
  "Technical Sergeant",
  "Trooper",
  "Trumpeter",
  "Under Officer",
  "Vice Admiral",
  "Warrant Officer",
  "Warrant Officer 1",
  "Warrant Officer Class 1 (WO1)",
  "Warrant Officer Class 2 (WO2)",
  "Wing Commander",
] as const;

export const MILITARY_RANKS: readonly string[] = Array.from(new Set(MILITARY_RANK_LINES)).sort((a, b) =>
  a.localeCompare(b, "en", { sensitivity: "base" }),
);

const RANK_ALIASES: Record<string, readonly string[]> = {
  "Able Seaman": ["AB", "A/B"],
  "Acting Sub-Lieutenant": ["A/SLt"],
  Admiral: ["Adm"],
  "Admiral of the Fleet": ["AF"],
  "Air Chief Marshal": ["ACM"],
  "Air Commodore": ["Air Cdre"],
  "Air Marshal": ["AM"],
  "Air Vice-Marshal": ["AVM"],
  Airman: ["Amn"],
  "Airman Basic": ["AB"],
  "Airman First Class": ["A1C"],
  Apprentice: ["App"],
  Bombardier: ["Bdr"],
  Brigadier: ["Brig"],
  "Brigadier General": ["BG", "Brig Gen"],
  Cadet: ["Cdt"],
  Captain: ["Capt"],
  "Chief Master Sergeant": ["CMSgt"],
  "Chief Master Sergeant of the Air Force": ["CMSAF"],
  "Chief Master Sergeant of the Space Force": ["CMSSF"],
  "Chief Petty Officer": ["CPO"],
  "Chief Warrant Officer 2": ["CWO2"],
  "Chief Warrant Officer 3": ["CWO3"],
  "Chief Warrant Officer 4": ["CWO4"],
  "Chief Warrant Officer 5": ["CWO5"],
  Colonel: ["Col"],
  "Colour Sergeant": ["CSgt"],
  "Command Sergeant Major": ["CSM"],
  Commander: ["Cdr"],
  Commodore: ["Cdre"],
  Corporal: ["Cpl"],
  Driver: ["Dvr"],
  Drummer: ["Dmr"],
  Ensign: ["Ens", "ENS"],
  "Field Marshal": ["FM"],
  "First Lieutenant": ["1st Lt", "1stLt"],
  "First Sergeant": ["1SG", "1stSgt"],
  "Fleet Admiral": ["FADM"],
  "Flight Lieutenant": ["Flt Lt"],
  "Flight Sergeant": ["FS", "Flt Sgt"],
  "Flying Officer": ["Fg Off"],
  General: ["Gen"],
  "General of the Air Force": ["GAF"],
  "General of the Army": ["GA"],
  "Group Captain": ["Gp Capt"],
  Guardsman: ["Gdsm"],
  Gunner: ["Gnr"],
  "Gunnery Sergeant": ["GySgt"],
  Havildar: ["Hav"],
  "Lance Corporal": ["LCpl"],
  "Leading Aircraftman": ["LAC"],
  "Leading Seaman": ["LS"],
  Lieutenant: ["Lt", "LT"],
  "Lieutenant (Junior Grade)": ["LTJG"],
  "Lieutenant Colonel": ["Lt Col", "LtCol"],
  "Lieutenant Commander": ["Lt Cdr", "LCDR"],
  "Lieutenant General": ["Lt Gen", "LtGen"],
  Major: ["Maj"],
  "Major General": ["Maj Gen", "MajGen"],
  "Master Chief Petty Officer": ["MCPO"],
  "Master Chief Petty Officer of the Coast Guard": ["MCPOCG"],
  "Master Chief Petty Officer of the Navy": ["MCPON"],
  "Master Corporal": ["MCpl"],
  "Master Gunnery Sergeant": ["MGySgt"],
  "Master Sergeant": ["MSgt", "MSG"],
  "Master Warrant Officer": ["MWO"],
  Midshipman: ["Mid"],
  "Officer Cadet": ["OCdt"],
  "Petty Officer": ["PO"],
  "Petty Officer First Class": ["PO1"],
  "Petty Officer Second Class": ["PO2"],
  "Petty Officer Third Class": ["PO3"],
  "Private First Class": ["PFC"],
  "Rear Admiral": ["RAdm", "RADM"],
  "Rear Admiral (Lower Half)": ["RDML"],
  "Rear Admiral (Upper Half)": ["RADM"],
  "Regimental Sergeant Major": ["RSM"],
  Rifleman: ["Rfn"],
  Sapper: ["Spr"],
  Sergeant: ["Sgt"],
  "Sergeant First Class": ["SFC"],
  "Sergeant Major": ["SgtMaj", "SGM"],
  Specialist: ["SPC"],
  "Squadron Leader": ["Sqn Ldr"],
  "Staff Sergeant": ["SSgt", "SSG"],
  "Sub-Lieutenant": ["SLt"],
  "Technical Sergeant": ["TSgt"],
  Trooper: ["Tpr"],
  "Vice Admiral": ["VAdm", "VADM"],
  "Warrant Officer": ["WO"],
  "Warrant Officer 1": ["WO1"],
  "Warrant Officer Class 1 (WO1)": ["WO1"],
  "Warrant Officer Class 2 (WO2)": ["WO2"],
  "Wing Commander": ["Wg Cdr"],
};

function normalizeRankToken(v: string): string {
  return v.toLowerCase().replace(/[^a-z0-9]/g, "");
}

export function rankMatchesQuery(rank: string, query: string): boolean {
  const q = normalizeRankToken(query);
  if (!q) return true;
  if (normalizeRankToken(rank).includes(q)) return true;
  const aliases = RANK_ALIASES[rank] ?? [];
  return aliases.some((a) => normalizeRankToken(a).includes(q));
}
